apiVersion: v1
kind: Service
metadata:
  name: mc-server-service
spec:
  type: LoadBalancer 
  selector:
    app: mc-server 
  ports:
    - name: minecraft
      protocol: TCP
      port: 25565
      targetPort: 25565
    - name: voice
      protocol: UDP
      port: 24454
      targetPort: 24454